--------------------------------------------------------
--  颇老捞 积己凳 - 格夸老-1岿-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRANSACTION_TABLE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TRANSACTION_TABLE" 
   (	"TRANSACTION_INDEX" NUMBER, 
	"CUSTOMER_NAME" VARCHAR2(20 BYTE), 
	"TRANSACTION_NAME" VARCHAR2(20 BYTE), 
	"TRANSACTION_DATE" VARCHAR2(20 BYTE), 
	"SUPPLY_PRICE" NUMBER, 
	"DEPARTMENT" VARCHAR2(20 BYTE), 
	"TRANSACTION_CODE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRANSACTION_USER_TABLE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TRANSACTION_USER_TABLE" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"USER_PASSWORD" VARCHAR2(20 BYTE), 
	"USER_AUTHORITY" NUMBER, 
	"DEPARTMENT" NUMBER, 
	"CONNECTED" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COST_ITEM_TABLE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."COST_ITEM_TABLE" 
   (	"COST_ITEM_INDEX" NUMBER, 
	"TRANSACTION_INDEX" NUMBER, 
	"SUPPLIER" VARCHAR2(20 BYTE), 
	"SUM" NUMBER, 
	"CREDIT" VARCHAR2(20 BYTE), 
	"CASH" VARCHAR2(20 BYTE), 
	"CARD" VARCHAR2(20 BYTE), 
	"NOTE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.TRANSACTION_TABLE
SET DEFINE OFF;
REM INSERTING into SYSTEM.TRANSACTION_USER_TABLE
SET DEFINE OFF;
Insert into SYSTEM.TRANSACTION_USER_TABLE (USER_ID,USER_PASSWORD,USER_AUTHORITY,DEPARTMENT,CONNECTED) values ('admin','admin',0,999,'logout');
REM INSERTING into SYSTEM.COST_ITEM_TABLE
SET DEFINE OFF;
